---
- name: Configure Devices via Native
  hosts: ios
  gather_facts: no

  tasks:
    - name: Import Host Variables
      include_vars:
        file: host_vars/ios1.yml
        name: vars

    - name: Display Intended Configuration
      debug:
        var: vars['openconfig-vlan:vlans'].vlan

    - name: Apply Configuration
      ios_vlan:
         vlan_id: "{{ item.config['vlan-id'] }}"
         name: "{{ item.config['name'] }}"
         state: present
      with_items: "{{ vars['openconfig-vlan:vlans'].vlan }}"
