---
- name: NETCONF
  hosts: all
  gather_facts: no

  tasks:
    - name: "Enable NETCONF"
      connection: network_cli
      junos_netconf:
      when: ansible_network_os == 'junos'

    - name: "Get Config via NETCONF"  
      connection: netconf
      netconf_get:
         source: running
         filter: "<configuration><system></system></configuration>"
      register: nc_output

    - name: "configure via netconf"
      connection: netconf
      netconf_config:
        content: "{{ lookup('file', './config.xml') }}"
      tags:
      - config_vlan

    - debug:
        msg: '{{ nc_output }}'
        
