---
- name: Configure Devices via NETCONF
  hosts: netconf
  gather_facts: no

  tasks:
    - name: "Enable NETCONF"
      connection: network_cli
      junos_netconf:
      when: ansible_network_os == 'junos'

    - name: "Convert host_var to OpenConfig Yang XML"
      command: "python ../scripts/convert.py -y ./host_vars/{{ inventory_hostname }}.yml"
      delegate_to: localhost
      register: yang_xml

    - name: "Display generated OpenConfig Yang XML"
      xml:
        xmlstring: '{{ yang_xml.stdout }}'
        pretty_print : yes
      delegate_to: localhost

    - name: "Apply Configuration"
      connection: netconf
      netconf_config:
        content: |
          <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
            {{ yang_xml.stdout }}
          </config>
